#!/usr/bin/python           

import socket               # Import socket module

dbfile = 'dbfile'	# database file to store requests

s = socket.socket()         # Create a socket object
host = socket.gethostname() # Get local machine name
port = 12345                # Reserve a port for your service.
s.bind((host, port))        # Bind to the port

s.listen(5)                 # Now wait for client connection.

reqnum = 1

print 'Server started.'

print 'can handle the fault?'

#f = open(dbfile, 'w')
while True:
   c, addr = s.accept()     # Establish connection with client.
   msg = c.recv(1024)
   print 'Got message (' + str(reqnum) + ') [' + msg + '] from', addr
   c.send('Request ' + str(reqnum) + ' received.')
   c.close()                # Close the connection

   f = open(dbfile, 'a')
   f.write(msg + '\n')
   f.close

   reqnum += 1
